@startuml client-states

[*] --> Hello

Hello : entry / send Hello message

Hello ---> Measurement : OK received
Hello --> [*] : ERROR received

Measurement --> Bye : n_probes echos received
Measurement --> [*] : ERROR received

Measurement : exit / print RTT and/or throughput

Bye --> WaitByeResponse

Bye : entry / send Bye message
WaitByeResponse : exit / close connection

WaitByeResponse --> [*] : OK received
WaitByeResponse -up-> WaitByeResponse : response timeout

@enduml
